# @package _global_

sample_rate: 32000
length: 262144 #2^18
channels: 2
log_every_n_steps: 1000
 
batch_size: 32
num_workers: 16
prefetch_factor: 8

fast_dev_run: null

wandb_offline: False
wandb_run_id: "h2vlsha7" #use to resume run

# only provide ckpt if you want to start from that ckpt
ckpt: ${logs_dir}/ckpts/2023-11-24-16-15-34/last.ckpt

model:
  _target_: main.models.DMAE
  lr: 1e-4
  lr_beta1: 0.95
  lr_beta2: 0.999
  lr_eps: 1e-6
  lr_weight_decay: 1e-3
  ema_beta: 0.995
  ema_power: 0.7

  model:
    _target_: main.models.get_pretrained_diffae_from_huggingface


datamodule:
  _target_: main.datamodules.AudioDataModule
  datasets: 
  - 
    _target_: main.datamodules.XenoCantoAudioDataset
    sample_rate: ${sample_rate}
    channels: ${channels}
    data_dir: /data/xeno-canto/xeno_canto_full_32000
    metadata_dir: ${meta_dir}/xeno_canto
    
  - 
    _target_: main.datamodules.BergmanAudioDataset
    sample_rate: ${sample_rate}
    channels: ${channels}
    metadata_file: ${meta_dir}/bergman_en.csv
    
  batch_size: ${batch_size}
  crop_length: ${length}
  num_workers: ${num_workers}
  shuffle: True
  pin_memory: True
  prefetch_factor: ${prefetch_factor}
  train_val_test_split: [0.85, 0.1, 0.05]
  seed: ${seed}
  verbose: True


callbacks:
  rich_progress_bar:
    _target_: pytorch_lightning.callbacks.RichProgressBar

  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: "valid_loss"   # name of the logged metric which determines when model is improving
    mode: "min"             # can be "max" or "min"
    save_top_k: 2           # save k best models (determined by above metric in above mode)
    save_last: True         # additionally always save model from last epoch
    verbose: False
    dirpath: ${logs_dir}/ckpts/${now:%Y-%m-%d-%H-%M-%S}
    filename: '{epoch:02d}-{valid_loss:.3f}'

  model_summary:
    _target_: pytorch_lightning.callbacks.RichModelSummary
    max_depth: 2


loggers:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    project: "audioDiffusion"
    entity: "mx-wurthmann"
    offline: ${wandb_offline}  # set True to store all logs only locally
    job_type: "train"
    id: ${wandb_run_id}
    group: ""
    save_dir: ${logs_dir}


trainer:
  _target_: pytorch_lightning.Trainer
  devices: -1 # Set `1` to train on GPU, `0` to train on CPU only, and `-1` to train on all GPUs, default `0`
  precision: 32 # Precision used for tensors, default `32`
  accelerator: "gpu"
  strategy:
    _target_: pytorch_lightning.strategies.DDPStrategy
    find_unused_parameters: False
  min_epochs: 0
  max_epochs: -1
  # profiler: "simple"
  enable_model_summary: False
  log_every_n_steps: 1 # Logs metrics every N batches
  check_val_every_n_epoch: null
  limit_val_batches: 20
  val_check_interval: ${log_every_n_steps}
  fast_dev_run: ${fast_dev_run}
